chore: add action to build che-code-dev image

diff --git a/.github/workflows/build-dev-image.yaml b/.github/workflows/build-dev-image.yaml
--- a/.github/workflows/build-dev-image.yaml
+++ b/.github/workflows/build-dev-image.yaml
@@ -51,17 +51,15 @@ jobs:
 
       - name: Build Che-Code Docker image
         run: |
-          PR_NUMBER="${{github.event.number}}"
-          # PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
+          echo "${{ github.event.number }}" > PR_NUMBER
           echo "Pull request $PR_NUMBER"
 
-          # if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
-          #   echo "Pull request number invalid"
-          #   exit 1
-          # fi
+          if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
+            echo "Pull request number invalid"
+            exit 1
+          fi
 
           echo "_PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
-
 
           DEV_IMAGE_NAME=quay.io/che-incubator-pull-requests/che-code-dev:pr-${PR_NUMBER}-dev-amd64
           echo "Dev image $DEV_IMAGE_NAME"
