merge release and insiders publish jobs

diff --git a/.github/workflows/image-publish.yml b/.github/workflows/image-publish.yml
--- a/.github/workflows/image-publish.yml
+++ b/.github/workflows/image-publish.yml
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2021 Red Hat, Inc.
+# Copyright (c) 2022 Red Hat, Inc.
 # This program and the accompanying materials are made
 # available under the terms of the Eclipse Public License 2.0
 # which is available at https://www.eclipse.org/legal/epl-2.0/
@@ -11,10 +11,11 @@ name: image-publish-insiders
 
 on:
   push:
-    branches: [ main ]
+    branches: 
+      - main
+      - '7.*.*'
 
 jobs:
-
   build:
     name: build
     strategy:
@@ -42,6 +43,15 @@ jobs:
     needs: build
     runs-on: ubuntu-20.04
     steps:
+      - name: Set variables:
+        run: |
+          BRANCH_NAME=${{ github.ref }}
+          BRANCH_NAME=${BRANCH_NAME##*/}
+          if [[ $BRANCH_NAME == 'refs/heads/main' ]]; then
+            echo "BRANCH_NAME=insiders" >> $GITHUB_ENV
+          else [[ $BRANCH_NAME =~ ^7\.[0-9]+\.[0-9]+$ ]]; then
+            echo "BRANCH_NAME=$BRANCH_NAME >> $GITHUB_ENV
+          fi
       - name: Checkout
         uses: actions/checkout@v2
       - name: Download linux-libc-amd64 image
@@ -64,10 +74,14 @@ jobs:
       - name: Docker Build and Push
         run: |
           SHORT_SHA1=$(git rev-parse --short=7 HEAD)
-          docker buildx build --platform linux/amd64 -f build/dockerfiles/assembly.Dockerfile --push -t quay.io/che-incubator/che-code:insiders -t quay.io/che-incubator/che-code:next -t quay.io/che-incubator/che-code:insiders-${SHORT_SHA1} .
+          if [[ ${{ env.BRANCH_NAME }} == main ]]; then
+            docker buildx build --platform linux/amd64 -f build/dockerfiles/assembly.Dockerfile --push -t quay.io/che-incubator/che-code:insiders -t quay.io/che-incubator/che-code:next -t quay.io/che-incubator/che-code:insiders-${SHORT_SHA1} .
+          else if [[ ${{ env.BRANCH_NAME }} =~ ^7\.[0-9]+\.[0-9]+$ ]]; then
+            docker buildx build --platform linux/amd64 -f build/dockerfiles/assembly.Dockerfile --push -t quay.io/che-incubator/che-code:${{env.BRANCH_NAME}}  . 
   dev:
     name: dev
     runs-on: ubuntu-20.04
+    if: github.ref == 'refs/heads/main'
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -81,3 +95,18 @@ jobs:
         run: |
           SHORT_SHA1=$(git rev-parse --short=7 HEAD)
           docker buildx build --platform linux/amd64 -f build/dockerfiles/dev.Dockerfile --push -t quay.io/che-incubator/che-code-dev:insiders -t quay.io/che-incubator/che-code-dev:next -t quay.io/che-incubator/che-code-dev:insiders-${SHORT_SHA1} .
+      - name: Create failure MM message
+        if: ${{ failure() }} || {{ github.ref == 'refs/heads/main'}}
+        run: |
+          echo "{\"text\":\":no_entry_sign: Che Code ${{ github.event.inputs.version }} release has failed: https://github.com/che-incubator/che-code/actions/workflows/release.yml\"}" > mattermost.json
+      - name: Create success MM message
+        if: ${{ github.ref == 'refs/heads/main'}}
+        run: |
+          echo "{\"text\":\":white_check_mark: Che Code ${{ github.event.inputs.version }} has been released: https://quay.io/che-incubator/che-code:${{ github.event.inputs.version }}\"}" > mattermost.json
+      - name: Send MM message
+        if: ${{ success() }} || ${{ failure() }} || ${{ github.ref == 'refs/heads/main'}}
+        uses: mattermost/action-mattermost-notify@1.1.0
+        env:
+          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
+          MATTERMOST_CHANNEL: eclipse-che-releases
+          MATTERMOST_USERNAME: che-bot
