fix: PR check failed on login to quay.io
Signed-off-by: vitaliy-guliy <vgulyy@redhat.com>

diff --git a/.github/workflows/pr-check-build-che-code-image.yaml b/.github/workflows/pr-check-build-che-code-image.yaml
--- a/.github/workflows/pr-check-build-che-code-image.yaml
+++ b/.github/workflows/pr-check-build-che-code-image.yaml
@@ -48,6 +48,35 @@ jobs:
     needs: build
     steps:
 
+      - name: PR number
+        uses: dawidd6/action-download-artifact@v2
+        with:
+          workflow: ${{ github.event.workflow_run.workflow_id }}
+          name: pull-request-number
+      - name: Grab pull request number
+        run: |
+          pr_number=$(cat "PR_NUMBER")
+          if ! [[ "$pr_number" =~ ^[0-9]+$ ]]; then
+            echo "pr number invalid"
+            exit 1
+          fi
+          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
+      - name: PR sha
+        uses: dawidd6/action-download-artifact@v2
+        with:
+          workflow: ${{ github.event.workflow_run.workflow_id }}
+          name: pull-request-sha
+      - name: Grab pull request sha1
+        run: |
+          pr_sha=$(cat "PR_SHA")
+          echo "PR_SHA=$pr_sha" >> $GITHUB_ENV
+      - name: Login to Quay.io
+        uses: docker/login-action@v2
+        with:
+          registry: quay.io
+          username: ${{ secrets.QUAY_PULL_REQUESTS_USERNAME }}
+          password: ${{ secrets.QUAY_PULL_REQUESTS_PASSWORD }}
+
       - name: Checkout che-code source code
         uses: actions/checkout@v3
 
@@ -65,12 +94,12 @@ jobs:
         with:
           image: "linux-musl-amd64"
 
-      - name: Login to Quay.io
-        uses: docker/login-action@v2
-        with:
-          registry: quay.io
-          username: ${{ secrets.QUAY_PULL_REQUESTS_USERNAME }}
-          password: ${{ secrets.QUAY_PULL_REQUESTS_PASSWORD }}
+      # - name: Login to Quay.io
+      #   uses: docker/login-action@v2
+      #   with:
+      #     registry: quay.io
+      #     username: ${{ secrets.QUAY_PULL_REQUESTS_USERNAME }}
+      #     password: ${{ secrets.QUAY_PULL_REQUESTS_PASSWORD }}
 
       - name: Display docker images
         run: |
